// app/utils/themes.js
import { Sparkles, Heart, Star, Cake, Gift, Flame, Leaf, CloudLightning } from "lucide-react";

export const OCCASION_THEMES = {
  birthday: {
    name: "Birthday",
    gradient: "from-purple-950 via-[#0d0716] to-[#05020a]",
    accentColor: "pink",
    themeClass: "theme-birthday",
    glowColor: "rgba(236, 72, 153, 0.4)",
    particleType: "star", // star, heart, petal, blossom
    gameItemType: "balloon", // balloon, heart, flower, star
    gameTitle: "Pop the Birthday Balloons!",
    gameSubtitle: "Pop 3 colorful balloons to unlock your special wishes!",
    ceremonyType: "cake", // cake, lantern, sparkler, flower
    ceremonyTitle: "Make a Wish & Blow Out the Candle!",
    ceremonySubtitle: "Blow into your microphone (or tap the candle) to blow it out!",
    giftType: "wrapped", // wrapped, velvet-ring, gold-chest
    giftTitle: "Your Birthday Present",
    giftSubtitle: "Drag the lid up to open your surprise!",
    galleryEmoji: "🎂",
  },
  anniversary: {
    name: "Anniversary",
    gradient: "from-[#1d0505] via-[#0b0101] to-[#000000]",
    accentColor: "rose",
    themeClass: "theme-anniversary",
    glowColor: "rgba(244, 63, 94, 0.4)",
    particleType: "heart",
    gameItemType: "heart",
    gameTitle: "Catch the Floating Hearts!",
    gameSubtitle: "Pop 3 drifting hearts to unlock your loving message!",
    ceremonyType: "lantern",
    ceremonyTitle: "Light the Eternal Lantern of Love",
    ceremonySubtitle: "Blow into your microphone (or tap the lantern) to light it up!",
    giftType: "velvet-ring",
    giftTitle: "A Token of Love",
    giftSubtitle: "Drag the lid up to open the ring box!",
    galleryEmoji: "❤️",
  },
  engagement: {
    name: "Engagement",
    gradient: "from-[#1d1005] via-[#090501] to-[#000000]",
    accentColor: "amber",
    themeClass: "theme-engagement",
    glowColor: "rgba(245, 158, 11, 0.4)",
    particleType: "heart",
    gameItemType: "ring-bubble",
    gameTitle: "Pop the Sparkling Bubbles!",
    gameSubtitle: "Pop 3 golden bubbles to reveal your special card!",
    ceremonyType: "sparkler",
    ceremonyTitle: "Light the Celebration Sparkler",
    ceremonySubtitle: "Blow into your microphone (or tap the sparkler) to ignite it!",
    giftType: "velvet-ring",
    giftTitle: "A Promise of Tomorrow",
    giftSubtitle: "Drag the lid up to open the box!",
    galleryEmoji: "💍",
  },
  wedding: {
    name: "Wedding",
    gradient: "from-[#151109] via-[#0a0804] to-[#000000]",
    accentColor: "yellow",
    themeClass: "theme-wedding",
    glowColor: "rgba(234, 179, 8, 0.4)",
    particleType: "petal",
    gameItemType: "crystal-bubble",
    gameTitle: "Pop the Marriage Bubbles!",
    gameSubtitle: "Pop 3 crystal bubbles to unveil your congratulations!",
    ceremonyType: "wedding-candles",
    ceremonyTitle: "Light the Sacred Wedding Candle",
    ceremonySubtitle: "Blow into your microphone (or tap the wick) to light the flame!",
    giftType: "gold-chest",
    giftTitle: "The Wedding Gift Chest",
    giftSubtitle: "Drag the lid up to unlock the treasure!",
    galleryEmoji: "🥂",
  },
  "mother-day": {
    name: "Mother's Day",
    gradient: "from-[#1a0815] via-[#0d040b] to-[#040103]",
    accentColor: "pink",
    themeClass: "theme-mothers-day",
    glowColor: "rgba(244, 114, 182, 0.4)",
    particleType: "blossom",
    gameItemType: "flower",
    gameTitle: "Gather the Cherry Blossoms!",
    gameSubtitle: "Tap 3 blossoms to reveal your custom wishes!",
    ceremonyType: "flower-grow",
    ceremonyTitle: "Water & Grow a Magical Rose",
    ceremonySubtitle: "Blow into your microphone (or tap the bud) to bloom the flower!",
    giftType: "wrapped",
    giftTitle: "A Gift for the Best Mom",
    giftSubtitle: "Drag the lid up to open your surprise!",
    galleryEmoji: "🌸",
  },
  "father-day": {
    name: "Father's Day",
    gradient: "from-[#051118] via-[#02080d] to-[#000000]",
    accentColor: "blue",
    themeClass: "theme-fathers-day",
    glowColor: "rgba(59, 130, 246, 0.4)",
    particleType: "star",
    gameItemType: "star",
    gameTitle: "Catch the Shooting Stars!",
    gameSubtitle: "Pop 3 stars to open your fatherly messages!",
    ceremonyType: "lantern",
    ceremonyTitle: "Release the Sky Lanterns",
    ceremonySubtitle: "Blow into your microphone (or tap the match) to launch the lanterns!",
    giftType: "gold-chest",
    giftTitle: "A Special Gift for Dad",
    giftSubtitle: "Drag the lid up to unlock your package!",
    galleryEmoji: "👔",
  }
};

export function getTheme(occasion) {
  return OCCASION_THEMES[occasion] || OCCASION_THEMES.birthday;
}
